import path from 'node:path';
import type { Finding, ScanResult, Severity } from '../../types/index.js';
import { countBySeverity } from '../../utils/severity-counts.js';

const SEVERITY_COLOR: Record<Severity, string> = {
  critical: '#b91c1c',
  high: '#dc2626',
  medium: '#d97706',
  low: '#0891b2',
  info: '#6b7280',
};

const PAGE_STYLE = 'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#111;}header{border-bottom:1px solid #e5e7eb;padding-bottom:1rem;margin-bottom:1.5rem;}h1{margin:0;font-size:1.75rem;}.meta{color:#6b7280;font-size:.875rem;margin-top:.25rem;}.summary{display:flex;gap:.5rem;margin:1rem 0;flex-wrap:wrap;}.badge{padding:.25rem .75rem;border-radius:999px;color:#fff;font-size:.875rem;font-weight:600;}.finding{margin:.5rem 0;padding:.5rem;border:1px solid #e5e7eb;border-radius:6px;background:#fafafa;}.finding summary{cursor:pointer;display:flex;gap:.75rem;align-items:center;}.finding .sev{color:#fff;padding:.125rem .5rem;border-radius:4px;font-size:.75rem;font-weight:700;}.finding code{background:#e5e7eb;padding:.125rem .375rem;border-radius:3px;font-size:.875rem;}.finding .loc{color:#2563eb;font-family:monospace;font-size:.875rem;}.finding .title{flex:1;font-weight:500;}.finding .body{margin-top:.75rem;padding:.75rem;background:#fff;border-left:3px solid #d1d5db;}.finding .body pre{background:#1e293b;color:#e2e8f0;padding:.75rem;border-radius:4px;overflow-x:auto;font-size:.8125rem;}.finding pre code{background:transparent;padding:0;}footer{margin-top:2rem;color:#6b7280;font-size:.875rem;text-align:center;}';

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function safeHref(url: string): string {
  const trimmed = url.trim();
  return /^https?:\/\//i.test(trimmed) ? escape(trimmed) : '#';
}

function findingHtml(f: Finding, rootDir: string): string {
  const rel = path.relative(rootDir, f.location.path) || f.location.path;
  return `
  <details class="finding sev-${f.severity}">
    <summary>
      <span class="sev" style="background:${SEVERITY_COLOR[f.severity]}">${f.severity.toUpperCase()}</span>
      <code>${escape(f.ruleId)}</code>
      <span class="loc">${escape(rel)}:${f.location.startLine}</span>
      <span class="title">${escape(f.title)}</span>
    </summary>
    <div class="body">
      <p>${escape(f.description)}</p>
      <p><strong>Source:</strong> ${escape(f.evidence.primarySource)}</p>
      ${f.evidence.cveIds?.length ? `<p><strong>CVEs:</strong> ${f.evidence.cveIds.map(escape).join(', ')}</p>` : ''}
      ${f.evidence.references.length ? `<p><strong>References:</strong><ul>${f.evidence.references.map((r) => `<li><a href="${safeHref(r)}">${escape(r)}</a></li>`).join('')}</ul></p>` : ''}
      <p><strong>Remediation:</strong> ${escape(f.remediation.summary)}</p>
      ${f.location.snippet ? `<pre><code>${escape(f.location.snippet)}</code></pre>` : ''}
    </div>
  </details>`;
}

export function renderHtml(result: ScanResult, rootDir: string): string {
  const counts = countBySeverity(result.findings);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PromptShield Report</title>
<style>${PAGE_STYLE}</style>
</head>
<body>
<header>
  <h1>PromptShield Report</h1>
  <div class="meta">v${result.toolVersion} · scanned ${result.scannedFiles.length} files in ${result.durationMs}ms · signatures ${result.signaturesVersion}</div>
  <div class="summary">
    <span class="badge" style="background:${SEVERITY_COLOR.critical}">Critical: ${counts.critical}</span>
    <span class="badge" style="background:${SEVERITY_COLOR.high}">High: ${counts.high}</span>
    <span class="badge" style="background:${SEVERITY_COLOR.medium}">Medium: ${counts.medium}</span>
    <span class="badge" style="background:${SEVERITY_COLOR.low}">Low: ${counts.low}</span>
  </div>
</header>
<main>
${result.findings.length === 0 ? '<p>✓ No findings.</p>' : result.findings.map((f) => findingHtml(f, rootDir)).join('\n')}
</main>
<footer>Generated by <a href="https://promptshield.dev">PromptShield</a> · MIT licensed</footer>
</body>
</html>
`;
}
