import path from 'node:path';
import type { Finding, ScanResult, Severity } from '../../types/index.js';
import { countBySeverity } from '../../utils/severity-counts.js';

/**
 * Render scan results as Markdown
 */
export function renderMarkdown(result: ScanResult, rootDir: string): string {
  const lines: string[] = [];

  // Title
  lines.push('# PromptShield Scan Report');
  lines.push('');

  // Metadata
  lines.push('## Scan Summary');
  lines.push('');
  lines.push(`- **Scanned Root Path**: \`${rootDir}\``);
  lines.push(`- **Files Scanned**: ${result.scannedFiles.length}`);
  lines.push(`- **Total Findings**: ${result.findings.length}`);
  lines.push('');

  // Severity summary
  const counts = countBySeverity(result.findings);

  lines.push('## Severity Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| Critical | ${counts.critical} |`);
  lines.push(`| High     | ${counts.high} |`);
  lines.push(`| Medium   | ${counts.medium} |`);
  lines.push(`| Low      | ${counts.low} |`);
  lines.push(`| Info     | ${counts.info} |`);
  lines.push('');

  if (result.findings.length === 0) {
    lines.push('✓ No findings. AI tooling configuration looks clean.');
    lines.push('');
    return lines.join('\n');
  }

  // Group findings by severity
  const severityOrder: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];
  
  for (const severity of severityOrder) {
    const findingsForSeverity = result.findings.filter((f) => f.severity === severity);
    if (findingsForSeverity.length === 0) continue;

    lines.push(`## ${severity.charAt(0).toUpperCase() + severity.slice(1)} Severity Findings`);
    lines.push('');

    for (const f of findingsForSeverity) {
      const rel = path.relative(rootDir, f.location.path) || f.location.path;
      
      lines.push(`### ${f.title}`);
      lines.push('');
      lines.push(`- **Rule ID**: \`${f.ruleId}\``);
      lines.push(`- **Location**: \`${rel}:${f.location.startLine}\``);
      lines.push(`- **Severity**: ${severity.toUpperCase()}`);
      lines.push('');
      lines.push(`**Description**: ${f.description}`);
      lines.push('');
      lines.push(`**Source**: ${f.evidence.primarySource}`);
      lines.push('');
      
      if (f.evidence.cveIds && f.evidence.cveIds.length > 0) {
        lines.push(`**CVEs**: ${f.evidence.cveIds.join(', ')}`);
        lines.push('');
      }
      
      if (f.evidence.references.length > 0) {
        lines.push('**References**:');
        for (const ref of f.evidence.references) {
          lines.push(`- ${ref}`);
        }
        lines.push('');
      }
      
      lines.push(`**Remediation**: ${f.remediation.summary}`);
      lines.push('');
      
      if (f.remediation.autoFixAvailable) {
        lines.push('> 💡 Auto-fix available. Run `npx promptshield fix` to remediate.');
        lines.push('');
      }
      
      if (f.location.snippet) {
        lines.push('**Code Snippet**:');
        lines.push('```');
        lines.push(f.location.snippet);
        lines.push('```');
        lines.push('');
      }
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`Generated by [PromptShield](https://promptshield.dev) v${result.toolVersion}`);
  lines.push('');

  return lines.join('\n');
}

// Made with Bob
